const STORE='jt_turbo_local_v14';
let db=JSON.parse(localStorage.getItem(STORE)||'{"orders":[],"history":[]}');
let map=null,me=null,stream=null,currentCameraOrder=null;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function save(){localStorage.setItem(STORE,JSON.stringify(db));}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function show(id){['home','setup','route','history'].forEach(x=>$(x).hidden=x!==id);if(id==='route'){setTimeout(()=>{if(!map)initMap();map.invalidateSize();render();},80)}}
function phone(v){let d=String(v||'').replace(/\D/g,'');if((d.length===10||d.length===11)&&!d.startsWith('55'))d='55'+d;return d}
function nextId(){let n=db.orders.map(o=>parseInt(o.id,10)).filter(Number.isFinite);return String((Math.max(0,...n)+1)).padStart(3,'0')}
function address(o){return [o.address,o.number,o.complement,o.city].filter(Boolean).join(', ')}
function addOrders(list){const ids=new Set(db.orders.map(o=>o.id));list.forEach(o=>{if(ids.has(o.id))o.id=nextId();ids.add(o.id);db.orders.push(o)});save()}
function parse(line,i){const p=line.split(';').map(x=>x.trim());return{id:p[0]||String(i+1).padStart(3,'0'),client:p[1]||'',phone:phone(p[2]),address:p[3]||'',number:p[4]||'',complement:p[5]||'',city:p[6]||'',notes:'',lat:null,lng:null,status:'pending',priority:0}}
function render(){const list=db.orders;const f=$('filter').value;let visible=list;if(f==='pending')visible=list.filter(o=>o.status!=='done');if(f==='gps')visible=list.filter(o=>o.lat!=null&&o.status!=='done');if(f==='done')visible=list.filter(o=>o.status==='done');$('filterInfo').textContent=`${visible.length} de ${list.length} entregas`;$('stats').innerHTML=`<div>📦 <b>${list.length}</b><small>pacotes</small></div><div>📍 <b>${list.filter(o=>o.lat!=null).length}</b><small>com GPS</small></div><div>✅ <b>${list.filter(o=>o.status==='done').length}</b><small>entregues</small></div>`;$('orders').innerHTML=visible.map((o,i)=>`<article class="order ${o.status==='done'?'done':''}"><div class="orderTop"><b>#${esc(o.id)} • ${esc(o.client||'Sem nome')}</b><span>${o.lat!=null?'📍 GPS':'⚠️ sem GPS'}</span></div><div>${esc(address(o)||'Endereço não informado')}</div><small>${esc(o.notes||'')}</small><div class="row"><button onclick="requestOne('${esc(o.id)}')" class="wa">📲 Pedir GPS</button><button onclick="openLoc('${esc(o.id)}')">📍 Local</button><button onclick="editOne('${esc(o.id)}')">✏️ Editar</button>${o.lat!=null?`<button onclick="navigate('${esc(o.id)}')">🧭 Navegar</button>`:`<button onclick="geocode('${esc(o.id)}')">🔎 Localizar</button>`}<button onclick="toggleDone('${esc(o.id)}')">${o.status==='done'?'↩ Reabrir':'✓ Entregue'}</button></div></article>`).join('');const next=list.find(o=>o.status!=='done');$('nextCard').innerHTML=next?`<b>📦 Próxima entrega</b><h3>#${esc(next.id)} • ${esc(next.client)}</h3><p>${esc(address(next)||'Sem endereço')}</p>${next.lat!=null?`<button class="primary" onclick="navigate('${esc(next.id)}')">🧭 Navegar para próxima</button>`:'<button onclick="openLoc(\''+esc(next.id)+'\')">📍 Adicionar localização</button>'}`:'<b>🎉 Nenhuma entrega pendente.</b>';drawMap()}
function initMap(){map=L.map('map').setView([-15.78,-47.93],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}
function drawMap(){if(!map)return;map.eachLayer(l=>{if(l instanceof L.Marker||l instanceof L.CircleMarker||l instanceof L.Polyline)map.removeLayer(l)});const pts=[];db.orders.filter(o=>o.lat!=null&&o.status!=='done').forEach(o=>{const m=L.marker([o.lat,o.lng]).addTo(map).bindPopup(`<b>#${esc(o.id)} ${esc(o.client)}</b><br>${esc(address(o))}<br><button onclick="navigate('${esc(o.id)}')">🧭 Navegar</button>`);pts.push([o.lat,o.lng])});if(me)L.circleMarker(me,{radius:8}).addTo(map).bindPopup('📍 Você');if(pts.length>1)L.polyline((me?[me]:[]).concat(pts)).addTo(map);if(pts.length&&!me)map.fitBounds(pts,{padding:[20,20]})}
function locate(){if(!navigator.geolocation)return toast('GPS não disponível.');navigator.geolocation.getCurrentPosition(p=>{me=[p.coords.latitude,p.coords.longitude];$('gpsState').textContent=`GPS ativo • ±${Math.round(p.coords.accuracy)} m`;if(map)map.setView(me,16);drawMap()},()=>toast('Permita a localização no navegador.'),{enableHighAccuracy:true,timeout:15000,maximumAge:3000})}
function navigate(id){const o=db.orders.find(x=>x.id===id);if(!o?.lat)return toast('Esse pedido ainda não tem GPS.');location.href=`https://www.google.com/maps/dir/?api=1&destination=${o.lat},${o.lng}&travelmode=driving`}
function requestOne(id){const o=db.orders.find(x=>x.id===id);if(!o?.phone)return toast('Cadastre o WhatsApp do cliente.');const text=`Olá, ${o.client||'tudo bem'}! 🚚 Sou o entregador da J&T. Para agilizar sua entrega, envie sua localização atual pelo WhatsApp: 📎 > Localização > Enviar localização atual. Obrigado!`;location.href='https://wa.me/'+o.phone+'?text='+encodeURIComponent(text)}
function requestAll(){const p=db.orders.filter(o=>o.status!=='done'&&o.lat==null&&o.phone);if(!p.length)return toast('Não há pendentes com WhatsApp.');requestOne(p[0].id);toast(`WhatsApp aberto para ${p[0].client||p[0].id}`)}
function optimize(){const a=db.orders.filter(o=>o.status!=='done'&&o.lat!=null);if(a.length<2)return toast('Preciso de pelo menos 2 entregas com GPS.');const start=me||[a[0].lat,a[0].lng];const dist=(x,y)=>Math.hypot((x.lat-y[0])*111,(x.lng-y[1])*100);let left=[...a],out=[],cur=start;while(left.length){left.sort((x,y)=>dist(x,cur)-dist(y,cur));const o=left.shift();out.push(o);cur=[o.lat,o.lng]}const ids=new Set(out.map(o=>o.id));db.orders=[...out,...db.orders.filter(o=>!ids.has(o.id))];save();render();toast(`Rota organizada com ${out.length} pontos GPS`)}
function openLoc(id){const o=db.orders.find(x=>x.id===id);$('locOrderId').value=id;$('locOrderLabel').textContent=`#${o.id} • ${o.client}`;$('locationText').value='';$('locationDialog').showModal()}
function coords(s){let m=String(s).match(/@(-?\d+(?:\.\d+)?),(-?\d+(?:\.\d+)?)/);if(m)return [+m[1],+m[2]];m=String(s).match(/(-?\d{1,3}\.\d{4,})\s*[,; ]\s*(-?\d{1,3}\.\d{4,})/);return m?[+m[1],+m[2]]:null}
function saveLoc(e){e.preventDefault();const o=db.orders.find(x=>x.id===$('locOrderId').value),c=coords($('locationText').value);if(!c)return toast('Cole um link do Google Maps ou latitude,longitude.');o.lat=c[0];o.lng=c[1];o.locationSource='manual/WhatsApp';save();$('locationDialog').close();render();toast('📍 Localização salva')}
async function paste(){try{$('locationText').value=await navigator.clipboard.readText();toast('Localização colada.')}catch(e){toast('Cole manualmente no campo.')}}
function editOne(id){const o=db.orders.find(x=>x.id===id);$('editId').value=id;$('editName').value=o.client||'';$('editPhone').value=o.phone||'';$('editAddress').value=o.address||'';$('editNumber').value=o.number||'';$('editComplement').value=o.complement||'';$('editCity').value=o.city||'';$('editNotes').value=o.notes||'';$('editDialog').showModal()}
function saveEdit(e){e.preventDefault();const o=db.orders.find(x=>x.id===$('editId').value);o.client=$('editName').value.trim();o.phone=phone($('editPhone').value);o.address=$('editAddress').value.trim();o.number=$('editNumber').value.trim();o.complement=$('editComplement').value.trim();o.city=$('editCity').value.trim();o.notes=$('editNotes').value.trim();save();$('editDialog').close();render();toast('Entrega atualizada')}
async function geocode(id){const o=db.orders.find(x=>x.id===id),q=address(o);if(!q)return toast('Informe o endereço.');toast('Procurando endereço…');try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=br&q='+encodeURIComponent(q));const a=await r.json();if(!a.length)return toast('Endereço não encontrado.');o.lat=+a[0].lat;o.lng=+a[0].lon;o.locationSource='address';save();render();toast('📍 Endereço localizado')}catch(e){toast('Não consegui localizar agora. Use a localização do WhatsApp.')}}
function toggleDone(id){const o=db.orders.find(x=>x.id===id);o.status=o.status==='done'?'pending':'done';save();render()}
function addManual(){['fId','fName','fPhone','fAddress','fNumber','fComplement','fCity','fNotes'].forEach(id=>$(id).value='');$('addDialog').showModal()}
function saveAdd(e){e.preventDefault();const o={id:$('fId').value.trim()||nextId(),client:$('fName').value.trim(),phone:phone($('fPhone').value),address:$('fAddress').value.trim(),number:$('fNumber').value.trim(),complement:$('fComplement').value.trim(),city:$('fCity').value.trim(),notes:$('fNotes').value.trim(),lat:null,lng:null,status:'pending',priority:0};if(!o.client)return toast('Informe o nome.');addOrders([o]);$('addDialog').close();show('route');render();toast('📦 Entrega adicionada')}
function importList(){const lines=$('bulk').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return toast('Cole a lista primeiro.');addOrders(lines.map(parse));$('bulk').value='';show('route');render();toast(`${lines.length} pacotes adicionados`)}
function demo(){$('bulk').value='001;João;61999999999;Rua Exemplo;12;QD 12 LT 4;Valparaíso de Goiás\n002;Maria;61888888888;Rua Central;100;Bloco B;Valparaíso de Goiás\n003;Carlos;61777777777;Avenida Brasil;45;QD 4 LT 8;Valparaíso de Goiás'}
function clearSetup(){$('bulk').value=''}
async function cameraOpen(){currentCameraOrder=null;$('cameraName').value='';$('cameraPhone').value='';$('cameraAddress').value='';$('cameraNumber').value='';$('cameraCity').value='Valparaíso de Goiás';$('cameraDialog').showModal();try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('cameraVideo').srcObject=stream;$('cameraStatus').textContent='📷 Câmera ativa. Aponte para a etiqueta e use Ler dados da imagem.'}catch(e){$('cameraStatus').textContent='Câmera bloqueada. Verifique a permissão do navegador.'}}
function cameraClose(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}$('cameraDialog').close()}
async function ocr(){if(!stream)return toast('Abra a câmera primeiro.');const v=$('cameraVideo'),c=$('cameraCanvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);$('cameraStatus').textContent='🔎 Lendo imagem…';try{const r=await Tesseract.recognize(c,'por+eng');const text=r.data.text;parseOCR(text);$('cameraStatus').textContent='Confira os campos antes de salvar.'}catch(e){$('cameraStatus').textContent='Não consegui ler automaticamente. Preencha os campos.'}}
function parseOCR(t){const lines=t.split(/\n+/).map(x=>x.trim()).filter(Boolean);const ph=t.match(/(?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?9?\d{4}[\s-]?\d{4}/);if(ph)$('cameraPhone').value=phone(ph[0]);const nm=lines.find(x=>/^[A-Za-zÀ-ÿ ]{5,40}$/.test(x)&&!/(rua|avenida|quadra|setor|lote)/i.test(x));if(nm)$('cameraName').value=nm;const ad=lines.find(x=>/(rua|avenida|av\.?|quadra|qd\.?|setor|lote|residencial)/i.test(x));if(ad)$('cameraAddress').value=ad.replace(/\s+/g,' ');const no=t.match(/(?:n[ºo°]?\s*)?(\d{1,5})/i);if(no)$('cameraNumber').value=no[1]}
function saveCamera(){const o={id:nextId(),client:$('cameraName').value.trim(),phone:phone($('cameraPhone').value),address:$('cameraAddress').value.trim(),number:$('cameraNumber').value.trim(),complement:'',city:$('cameraCity').value.trim(),notes:'Adicionado pela câmera',lat:null,lng:null,status:'pending',priority:0};if(!o.client&&!o.address&&!o.phone)return toast('Leia os dados ou preencha algum campo.');addOrders([o]);cameraClose();show('route');render();toast('📦 Cliente salvo; pronto para o próximo')}
function facade(){if(!stream)return toast('Abra a câmera primeiro.');toast('A foto da fachada é feita pela própria câmera; use a imagem capturada como referência do endereço.');ocr()}
function municipal(){$('municipalDialog').showModal()}
function share(){const text=db.orders.map(o=>`#${o.id} ${o.client} — ${address(o)}${o.lat!=null?' — '+o.lat+','+o.lng:''}`).join('\n');if(navigator.share)navigator.share({title:'J&T Turbo',text});else navigator.clipboard?.writeText(text).then(()=>toast('Rota copiada'))}
function history(){const list=db.history||[];$('historyList').innerHTML=list.length?list.map(h=>`<article class="order"><b>${new Date(h.at).toLocaleString('pt-BR')}</b><div>${h.count} pacotes • ${h.done} entregues</div></article>`).join(''):'<p>Nenhuma rota finalizada ainda.</p>';show('history')}
function finish(){if(!db.orders.length)return toast('Não há entregas.');db.history.unshift({at:new Date().toISOString(),count:db.orders.length,done:db.orders.filter(o=>o.status==='done').length,orders:db.orders});db.orders=[];save();show('home');toast('Rota finalizada e salva no histórico')}
function waAuto(){$('waApiBase').value=localStorage.getItem('jt_wa_base')||'';$('waDialog').showModal()}
function follow(){const o=db.orders.find(x=>x.status!=='done'&&x.lat!=null);if(o)navigate(o.id);else toast('Nenhuma entrega com GPS pendente.')}
function municipalSearch(){ $('municipalDialog').close();show('route');toast('Use o mapa como referência para setor, quadra e rua. A localização final deve ser confirmada pelo GPS.')}
$('startBtn').onclick=()=>db.orders.length?show('route'):show('setup');$('newRouteBtn').onclick=()=>show('setup');$('resumeBtn').onclick=()=>db.orders.length?show('route'):toast('Não há rota salva.');$('historyBtn').onclick=history;$('backHome').onclick=()=>show('home');$('importBtn').onclick=importList;$('addBtn').onclick=addManual;$('demoBtn').onclick=demo;$('clearSetup').onclick=clearSetup;$('saveAdd').onclick=saveAdd;$('cancelAdd').onclick=()=>$('addDialog').close();$('saveEdit').onclick=saveEdit;$('cancelEdit').onclick=()=>$('editDialog').close();$('saveLocation').onclick=saveLoc;$('cancelLocation').onclick=()=>$('locationDialog').close();$('pasteLocationBtn').onclick=paste;$('locateBtn').onclick=locate;$('notifyStartBtn').onclick=requestAll;$('sortBtn').onclick=optimize;$('waAllBtn').onclick=requestAll;$('followBtn').onclick=follow;$('addQuickBtn').onclick=addManual;$('cameraBtn').onclick=cameraOpen;$('municipalBtn').onclick=municipal;$('smartBtn').onclick=()=>{const p=db.orders.find(o=>o.status!=='done'&&o.lat==null);p?geocode(p.id):toast('Nenhum endereço pendente.')};$('waAutoBtn').onclick=waAuto;$('shareBtn').onclick=share;$('finishBtn').onclick=finish;$('closeHistory').onclick=()=>show('home');$('filter').onchange=render;$('closeWa').onclick=()=>$('waDialog').close();$('saveWaBase').onclick=()=>{localStorage.setItem('jt_wa_base',$('waApiBase').value.trim());$('waStatus').textContent='Servidor salvo. O envio oficial depende de backend + credenciais Meta.'};$('waTest').onclick=()=>{$('waStatus').textContent='Modo local ativo. Cloud API ainda não configurada.'};$('closeCamera').onclick=cameraClose;$('scanBothBtn').onclick=ocr;$('scanNameBtn').onclick=ocr;$('scanPhoneBtn').onclick=ocr;$('captureFacadeBtn').onclick=facade;$('saveCameraBtn').onclick=saveCamera;$('closeMunicipal').onclick=()=>$('municipalDialog').close();$('municipalSearch').onclick=municipalSearch;
window.requestOne=requestOne;window.openLoc=openLoc;window.editOne=editOne;window.navigate=navigate;window.geocode=geocode;window.toggleDone=toggleDone;
show(db.orders.length?'route':'home');if(db.orders.length)setTimeout(()=>{initMap();render()},100);
