const SID='mobile';let session={id:SID,orders:[]},map=null,me=null,watchId=null,markers=[],routeLine=null,filter='all',lastDriverSync=0;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const STORE='jt_turbo_local_v4';
function localDB(){try{return JSON.parse(localStorage.getItem(STORE)||'{\"session\":{\"id\":\"mobile\",\"orders\":[]},\"history\":[]}')}catch(e){return {session:{id:'mobile',orders:[]},history:[]}}}
function saveDB(db){localStorage.setItem(STORE,JSON.stringify(db));}
async function api(url,opt={}){
  const db=localDB(); const method=(opt.method||'GET').toUpperCase();
  if(url.startsWith('/api/session?id=')) return db.session;
  if(url==='/api/history') return db.history||[];
  if(url==='/api/session/import' && method==='POST'){const body=JSON.parse(opt.body||'{}');db.session={id:body.sessionId||'mobile',orders:body.orders||[]};saveDB(db);return db.session;}
  if(url.startsWith('/api/order/') && method==='PATCH'){const body=JSON.parse(opt.body||'{}');const id=decodeURIComponent(url.split('/api/order/')[1]);const o=(db.session.orders||[]).find(x=>x.id===id);if(o&&body.patch)Object.assign(o,body.patch);saveDB(db);return {ok:true};}
  if(url==='/api/session/finish' && method==='POST'){const snapshot=JSON.parse(JSON.stringify(db.session));db.history=db.history||[];db.history.unshift({finishedAt:new Date().toISOString(),orders:snapshot.orders,stats:{packages:snapshot.orders.length,delivered:snapshot.orders.filter(x=>x.status==='done').length,gps:snapshot.orders.filter(x=>x.lat!=null).length}});db.session={id:'mobile',orders:[]};saveDB(db);return {ok:true,session:{stats:db.history[0].stats}};}
  if(url==='/api/driver/location' && method==='POST'){const body=JSON.parse(opt.body||'{}');localStorage.setItem('jt_driver_location',JSON.stringify(body));return {ok:true};}
  if(url.startsWith('/api/notify/')) return {ok:false,sent:0,localOnly:true};
  throw Error('API local não encontrada');
}function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function show(id){['home','setup','route','history'].forEach(x=>$(x).hidden=x!==id)}
async function load(){session=await api('/api/session?id='+SID);if(session.orders?.length){show('route');if(!map)initMap();render();drawMap();}else show('home')}
function initMap(){map=L.map('map',{zoomControl:false}).setView([-15.78,-47.93],11);L.control.zoom({position:'bottomright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}
function newRoute(){session={id:SID,orders:[]};show('setup');$('bulk').value=''}
function demo(){$('bulk').value='001;João;5561999999999;Rua Exemplo QD 12 LT 4, Brasília\n002;Maria;5561988888888;Condomínio Central Bloco B, Valparaíso\n003;Carlos;5561997777777;Av. Principal, QD 4 LT 8'}
async function importBulk(){const lines=$('bulk').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);const orders=lines.map((line,i)=>{let p=line.split(';');return{id:p[0]||String(i+1),client:p[1]||'',phone:(p[2]||'').replace(/\D/g,''),address:p.slice(3).join(';'),lat:null,lng:null,status:'pending',notes:'',priority:0}});if(!orders.length)return toast('Coloque pelo menos um pacote.');await api('/api/session/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:SID,orders})});await load();toast(`${orders.length} pacotes adicionados`)}
function addOne(){$('fId').value='';$('fName').value='';$('fPhone').value='';$('fAddress').value='';$('fNotes').value='';$('addDialog').showModal()}
async function saveOne(e){e.preventDefault();const o={id:$('fId').value||String(session.orders.length+1),client:$('fName').value,phone:$('fPhone').value,address:$('fAddress').value,notes:$('fNotes').value,lat:null,lng:null,status:'pending'};await api('/api/session/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:SID,orders:[...session.orders,o]})});$('addDialog').close();await load();toast('Entrega adicionada')}
function msg(o){return `Olá, ${o.client||'tudo bem'}! 🚚 Sou o entregador da J&T. Para agilizar sua entrega, poderia me enviar sua localização atual pelo WhatsApp? 📍\n\nNo WhatsApp: 📎 > Localização > Enviar sua localização atual.\n\nObrigado!`}
function requestWA(o){if(!o.phone)return toast('Este pacote não tem WhatsApp.');location.href='https://wa.me/'+o.phone+'?text='+encodeURIComponent(msg(o))}
function requestAll(){const p=session.orders.filter(o=>o.status!=='done'&&o.lat==null&&o.phone);if(!p.length)return toast('Não há pendentes com WhatsApp.');let i=0;const next=()=>{if(i>=p.length)return toast('Fila de WhatsApp concluída');requestWA(p[i++]);setTimeout(()=>{if(confirm(`Mensagem ${i}/${p.length}. Continuar para o próximo?`))next()},1800)};next()}
function nav(o){if(o.lat==null)return toast('Ainda sem GPS.');location.href=`https://www.google.com/maps/dir/?api=1&destination=${o.lat},${o.lng}&travelmode=driving`}
function dist(a,b,c,d){const R=6371,A=(c-a)*Math.PI/180,B=(d-b)*Math.PI/180;return 2*R*Math.asin(Math.sqrt(Math.sin(A/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(B/2)**2))}
function greedy(points,start){let left=[...points],out=[],cur=start;while(left.length){let bi=0,bd=Infinity;left.forEach((o,i)=>{const d=dist(cur[0],cur[1],o.lat,o.lng)-o.priority*.3;if(d<bd){bd=d;bi=i}});const o=left.splice(bi,1)[0];out.push(o);cur=[o.lat,o.lng]}return out}
function twoOpt(route,start){if(route.length<4)return route;let best=route.slice(),changed=true;const cost=a=>{let cur=start,s=0;for(const o of a){s+=dist(cur[0],cur[1],o.lat,o.lng);cur=[o.lat,o.lng]}return s};let bc=cost(best);let loops=0;while(changed&&loops++<80){changed=false;for(let i=0;i<best.length-2;i++)for(let j=i+1;j<best.length;j++){const cand=best.slice(0,i).concat(best.slice(i,j+1).reverse(),best.slice(j+1));const c=cost(cand);if(c+0.01<bc){best=cand;bc=c;changed=true}}}return best}
async function optimize(){const pts=session.orders.filter(o=>o.status!=='done'&&o.lat!=null);if(!pts.length)return toast('Aguardando localizações.');const start=me||[pts[0].lat,pts[0].lng];const ordered=twoOpt(greedy(pts,start),start);const ids=new Set(ordered.map(x=>x.id));const pending=session.orders.filter(o=>o.status!=='done'&&!ids.has(o.id));const done=session.orders.filter(o=>o.status==='done');await api('/api/session/import',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:SID,orders:[...ordered,...pending,...done]})});await load();toast(`Rota otimizada • ${ordered.length} GPS`)}
function syncDriver(p){if(Date.now()-lastDriverSync<15000)return;lastDriverSync=Date.now();api('/api/driver/location',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:SID,lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy})}).then(r=>{if(r.nearestId){$('nextEta').textContent=`ETA aprox. ${r.etaMin} min • ${r.nearestDistanceM} m`}}).catch(()=>{});}
function locate(){if(!navigator.geolocation)return toast('GPS não disponível.');navigator.geolocation.getCurrentPosition(p=>{me=[p.coords.latitude,p.coords.longitude];$('gpsState').textContent=`GPS ativo • ±${Math.round(p.coords.accuracy)} m`;syncDriver(p);drawMap();map.setView(me,16)},()=>toast('Permita localização no navegador.'),{enableHighAccuracy:true,timeout:15000,maximumAge:5000});if(!watchId)watchId=navigator.geolocation.watchPosition(p=>{me=[p.coords.latitude,p.coords.longitude];$('gpsState').textContent=`GPS ativo • ±${Math.round(p.coords.accuracy)} m`;syncDriver(p);drawMap()},()=>{}, {enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function drawMap(){if(!map)return;markers.forEach(m=>m.remove());markers=[];if(routeLine)routeLine.remove();const visible=session.orders.filter(o=>o.lat!=null&&o.status!=='done');visible.forEach((o,i)=>{const n=L.marker([o.lat,o.lng]).addTo(map).bindPopup(`<b>${esc(o.id)} • ${esc(o.client)}</b><br>${esc(o.address)}<br><br><button onclick="navById('${esc(o.id)}')">🧭 Navegar</button>`);markers.push(n)});if(me)L.circleMarker(me,{radius:8}).addTo(map).bindPopup('📍 Você').openPopup();const pts=visible.map(o=>[o.lat,o.lng]);if(pts.length>1)routeLine=L.polyline((me?[me]:[]).concat(pts),{weight:5,opacity:.65}).addTo(map);if(pts.length&&!me)map.fitBounds(pts,{padding:[25,25]})}
window.navById=id=>{const o=session.orders.find(x=>x.id===id);if(o)nav(o)};
async function done(id){const o=session.orders.find(x=>x.id===id);if(!o)return;await api('/api/order/'+encodeURIComponent(id),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:SID,patch:{status:o.status==='done'?'pending':'done'}})});await load();toast(o.status==='done'?'Entrega reaberta':'Entrega concluída')}
function nextStop(){const o=session.orders.find(x=>x.status!=='done'&&x.lat!=null);if(!o)return $('nextCard').innerHTML='<b>🎉 Nenhuma entrega com GPS pendente.</b>';const i=session.orders.indexOf(o);$('nextCard').innerHTML=`<small>PRÓXIMA PARADA</small><h2>#${esc(o.id)} • ${esc(o.client)}</h2><p>📍 ${esc(o.address||'Localização recebida pelo WhatsApp')}</p><div id="nextEta" class="eta">${o.etaMin?`ETA aprox. ${o.etaMin} min`:'ETA calculando…'}</div><div class="row"><button class="primary" onclick="navById('${esc(o.id)}')">🧭 Navegar agora</button><button onclick="notifyOne('${esc(o.id)}','arrival')">📲 Avisar chegada</button><button onclick="done('${esc(o.id)}')">✓ Entreguei</button></div>`}
function render(){const o=session.orders,d=o.filter(x=>x.status==='done').length,g=o.filter(x=>x.lat!=null&&x.status!=='done').length,p=o.filter(x=>x.lat==null&&x.status!=='done').length;$('stats').innerHTML=`<div class="stat"><b>${o.length}</b><span>pacotes</span></div><div class="stat"><b>${o.length-d}</b><span>pendentes</span></div><div class="stat good"><b>${g}</b><span>GPS</span></div><div class="stat"><b>${d}</b><span>entregues</span></div>`;$('filterInfo').textContent=`${p} aguardando localização`;nextStop();let list=o.filter(x=>filter==='all'||(filter==='done'&&x.status==='done')||(filter==='gps'&&x.lat!=null&&x.status!=='done')||(filter==='pending'&&x.status!=='done'));$('orders').innerHTML=list.map((x)=>{const i=o.indexOf(x);return `<article class="order ${x.status==='done'?'done':''}"><div class="top"><b>#${esc(x.id)} — ${esc(x.client)}</b><span class="badge ${x.status==='done'?'done':''}">${x.status==='done'?'ENTREGUE':x.lat!=null?'GPS OK':'AGUARDANDO'}</span></div><small>${esc(x.address||'Endereço não informado')}</small>${x.notes?`<div class="note">📝 ${esc(x.notes)}</div>`:''}<div class="row">${x.lat!=null&&x.status!=='done'?`<button class="mapbtn" onclick="navById('${esc(x.id)}')">🧭 Navegar</button>`:''}${x.status!=='done'&&x.lat==null?`<button class="wa" onclick="requestWA(session.orders[${i}])">💬 Pedir GPS</button>`:''}<button class="donebtn" onclick="done('${esc(x.id)}')">${x.status==='done'?'↩ Reabrir':'✓ Entregue'}</button></div></article>`}).join('')||'<p class="muted">Nada nesta categoria.</p>'}
async function history(){show('history');const hs=await api('/api/history');$('historyList').innerHTML=hs.length?hs.map(r=>`<article class="historyItem"><b>🚚 ${new Date(r.finishedAt).toLocaleString('pt-BR')}</b><div>${r.stats?.packages||r.orders.length} pacotes • ${r.stats?.delivered||0} entregues • ${r.stats?.gps||0} com GPS</div></article>`).join(''):'<p class="muted">Nenhuma rota finalizada ainda.</p>'}
async function notifyOne(id,kind){try{const r=await api('/api/notify/'+encodeURIComponent(id),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:SID,kind})});toast(r.ok?'WhatsApp enviado':'WhatsApp não enviado: configure a API oficial');await load()}catch(e){toast('Falha ao enviar WhatsApp')}}
async function routeStartNotify(){try{const r=await api('/api/notify/route-start',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:SID})});toast(`Avisos de saída: ${r.sent} enviados`)}catch(e){toast('Não foi possível enviar os avisos')}}
async function finish(){if(!confirm('Finalizar e salvar esta rota?'))return;const r=await api('/api/session/finish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:SID})});toast(`Rota salva • ${r.session.stats.packages} pacotes`);setTimeout(()=>load(),800)}
async function share(){const text=`J&T Turbo • ${session.orders.length} pacotes • ${session.orders.filter(o=>o.status==='done').length} entregues`;if(navigator.share)navigator.share({title:'J&T Turbo',text});else navigator.clipboard?.writeText(text).then(()=>toast('Resumo copiado'))}
$('newRouteBtn').onclick=newRoute;$('startBtn').onclick=newRoute;$('resumeBtn').onclick=load;$('historyBtn').onclick=history;$('closeHistory').onclick=()=>show('home');$('backHome').onclick=()=>show('home');$('importBtn').onclick=importBulk;$('addBtn').onclick=addOne;$('demoBtn').onclick=demo;$('clearSetup').onclick=()=>$('bulk').value='';$('addForm').onsubmit=saveOne;$('locateBtn').onclick=locate;$('notifyStartBtn').onclick=routeStartNotify;$('sortBtn').onclick=optimize;$('waAllBtn').onclick=requestAll;$('followBtn').onclick=locate;$('shareBtn').onclick=share;$('finishBtn').onclick=finish;$('filter').onchange=e=>{filter=e.target.value;render()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load().catch(()=>show('home'));
