const express=require('express');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const app=express();
app.use((req,res,next)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Headers','Content-Type,x-hub-signature-256');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.use(express.json({limit:'2mb',verify:(req,res,buf)=>{req.rawBody=buf}}));
app.use(express.static(path.join(__dirname,'public')));
const PORT=process.env.PORT||3000;
const DB=path.join(__dirname,'data','db.json');
fs.mkdirSync(path.dirname(DB),{recursive:true});
let db={sessions:{},whatsapp:{events:[],contacts:{}}};
try{if(fs.existsSync(DB))db={...db,...JSON.parse(fs.readFileSync(DB,'utf8'))}}catch(e){console.error(e.message)}
function save(){fs.writeFileSync(DB,JSON.stringify(db,null,2))}
const env={token:process.env.WA_ACCESS_TOKEN||'',phoneNumberId:process.env.WA_PHONE_NUMBER_ID||'',verifyToken:process.env.WA_VERIFY_TOKEN||'jt-turbo-verify',graphVersion:process.env.WA_GRAPH_VERSION||'v23.0',appSecret:process.env.WA_APP_SECRET||''};
app.get('/health',(req,res)=>res.json({ok:true,whatsappConfigured:!!(env.token&&env.phoneNumberId),webhook:'/webhook/whatsapp'}));
app.get('/webhook/whatsapp',(req,res)=>{const mode=req.query['hub.mode'],token=req.query['hub.verify_token'],challenge=req.query['hub.challenge'];if(mode==='subscribe'&&token===env.verifyToken)return res.status(200).send(challenge);res.sendStatus(403)});
function verifyMeta(req){if(!env.appSecret)return true;const sig=req.get('x-hub-signature-256')||'';if(!sig.startsWith('sha256='))return false;const expected='sha256='+crypto.createHmac('sha256',env.appSecret).update(req.rawBody||'').digest('hex');try{return crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected))}catch(e){return false}}
function normPhone(v){let d=String(v||'').replace(/\D/g,'');if(d.length===10||d.length===11)d='55'+d;return d}
function findOrder(phone){phone=normPhone(phone);for(const sid of Object.keys(db.sessions)){const s=db.sessions[sid];const o=(s.orders||[]).find(x=>normPhone(x.phone)===phone&&x.status!=='done');if(o)return{sid,o}}return null}
function parseAddressText(text){const t=String(text||'').trim();const m=t.match(/(?:rua|r\.|avenida|av\.|alameda|travessa|tv\.|quadra|q\.?d\.?)\s+(.+)/i);return{address:t,number:(t.match(/(?:n[ºo]?|número)\s*(\d+[A-Za-z-]?)/i)||[])[1]||''}}
async function graphSend(payload){if(!env.token||!env.phoneNumberId)throw new Error('WhatsApp Cloud API não configurada no servidor');const url=`https://graph.facebook.com/${env.graphVersion}/${env.phoneNumberId}/messages`;const r=await fetch(url,{method:'POST',headers:{Authorization:`Bearer ${env.token}`,'Content-Type':'application/json'},body:JSON.stringify({...payload,messaging_product:'whatsapp'})});const data=await r.json();if(!r.ok)throw new Error(data?.error?.message||'Falha na API do WhatsApp');return data}
async function sendText(to,text){return graphSend({to:normPhone(to),type:'text',text:{preview_url:false,body:text}})}
async function sendTemplate(to,name,language='pt_BR',components=[]){return graphSend({to:normPhone(to),type:'template',template:{name,language:{code:language},components}})}
async function sendLocation(to,lat,lng,name,address){return graphSend({to:normPhone(to),type:'location',location:{latitude:Number(lat),longitude:Number(lng),name:name||'J&T Turbo',address:address||''}})}
async function sendFlow(phone,order){const text=`Olá, ${order?.client||'tudo bem'}! 🚚\nSou da J&T Turbo e estou preparando sua entrega.\n\nPara confirmar: por favor envie aqui seu endereço completo (rua/avenida, número e complemento) e depois compartilhe sua localização atual 📍.\n\nAssim que receber, vou registrar tudo automaticamente para o entregador.`;return sendText(phone,text)}
app.post('/webhook/whatsapp',(req,res)=>{if(!verifyMeta(req))return res.sendStatus(401);res.sendStatus(200);setImmediate(async()=>{try{const body=req.body||{};for(const entry of(body.entry||[]))for(const change of(entry.changes||[])){const value=change.value||{};for(const m of(value.messages||[])){const phone=normPhone(m.from);const ev={id:m.id,phone,type:m.type,receivedAt:new Date().toISOString(),text:m.text?.body||'',location:m.location||null};db.whatsapp.events.unshift(ev);db.whatsapp.events=db.whatsapp.events.slice(0,1000);const match=findOrder(phone);if(!match)continue;const{sid,o}=match;if(m.type==='location'&&m.location){o.lat=Number(m.location.latitude);o.lng=Number(m.location.longitude);o.locationSource='whatsapp';o.locationAt=new Date().toISOString();await sendText(phone,`📍 Localização recebida, ${o.name||'obrigado'}! Já registrei na rota.`).catch(()=>{})}else if(m.type==='text'&&m.text?.body){const parsed=parseAddressText(m.text.body);if(!o.address){o.address=parsed.address;if(parsed.number)o.number=parsed.number;o.addressSource='whatsapp'}else if(!o.notes)o.notes=m.text.body;await sendText(phone,'✅ Recebi. Agora envie sua localização atual pelo WhatsApp: 📎 → Localização → Enviar localização atual.').catch(()=>{})}db.sessions[sid]=db.sessions[sid]}}save()}catch(e){console.error('Webhook:',e.message)}})});
app.post('/api/whatsapp/send-flow',async(req,res)=>{try{const{phone,order}=req.body||{};if(!phone)return res.status(400).json({ok:false,error:'phone obrigatório'});res.json({ok:true,result:await sendFlow(phone,order||{})})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/whatsapp/send-message',async(req,res)=>{try{const{phone,text}=req.body||{};if(!phone||!text)return res.status(400).json({ok:false,error:'phone e text obrigatórios'});res.json({ok:true,result:await sendText(phone,text)})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/whatsapp/send-template',async(req,res)=>{try{const{phone,name,language,components}=req.body||{};if(!phone||!name)return res.status(400).json({ok:false,error:'phone e name obrigatórios'});res.json({ok:true,result:await sendTemplate(phone,name,language||'pt_BR',components||[])})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/whatsapp/send-location',async(req,res)=>{try{const{phone,lat,lng,name,address}=req.body||{};if(!phone||lat==null||lng==null)return res.status(400).json({ok:false,error:'phone, lat e lng obrigatórios'});res.json({ok:true,result:await sendLocation(phone,lat,lng,name,address)})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.post('/api/whatsapp/send-batch',async(req,res)=>{try{const items=Array.isArray(req.body?.items)?req.body.items:[];const results=[];for(const x of items){try{results.push({phone:x.phone,ok:true,result:await sendText(x.phone,x.text)})}catch(e){results.push({phone:x.phone,ok:false,error:e.message})}}res.json({ok:true,results})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/api/whatsapp/events',(req,res)=>{const since=req.query.since?Number(req.query.since):0;res.json({ok:true,events:db.whatsapp.events.filter(e=>!since||Date.parse(e.receivedAt)>since).slice(0,200)})});
app.post('/api/whatsapp/session',(req,res)=>{const{sessionId,orders}=req.body||{};if(!sessionId)return res.status(400).json({ok:false});db.sessions[sessionId]={orders:orders||[]};save();res.json({ok:true})});
app.post('/api/sync',async(req,res)=>{try{const x=req.body||{};db.sessions[x.sessionId||'default']={...(db.sessions[x.sessionId||'default']||{}),...x};save();res.json({ok:true,syncedAt:new Date().toISOString()})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/api/route',async(req,res)=>{const a=req.query.a,b=req.query.b;if(!a||!b)return res.status(400).json({ok:false,error:'a e b obrigatórios'});try{const u='https://router.project-osrm.org/route/v1/driving/'+a+';'+b+'?overview=full&geometries=geojson&steps=true';const r=await fetch(u);res.status(r.status).json(await r.json())}catch(e){res.status(502).json({ok:false,error:e.message})}});
app.get('/api/whatsapp/config',(req,res)=>res.json({ok:true,configured:!!(env.token&&env.phoneNumberId),webhookPath:'/webhook/whatsapp',graphVersion:env.graphVersion}));
app.get(/.*/,(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log(`J&T Turbo server listening on ${PORT}`));