'use strict';
const KEY='jtTurboV19';
const CITY='Valparaíso de Goiás, GO, Brasil';
const CENTER=[-16.0651,-47.9757];
const NEIGH=['Cidade Jardins','Cidade Jardins - Etapa B','Jardim Céu Azul','Parque das Cachoeiras','Ypiranga','Valparaiso II','Parque Rio Branco','Chácaras Anhangüera','Valparaiso I - Etapa B','Residencial Florais do Planalto','Jardim Oriente','Unimorar','Pacaembu','Parque Araruama','Parque Marajó','Chácaras Araguaia','Parque Esplanada III','Setor de Chácaras Anhangüera B','Nova Vila Guaíra','Valparaiso I - Etapa C','Chácara Lourdes Meireles','Chácaras Ipanema','Setor de Chácaras Anhangüera C','Cruzeiro do Sul','Condomínio Residencial Parque dos Ipês','Parque Santa Rita de Cássia','Parque Esplanada V','Parque do Ipê','Morada Nobre','Parque São Bernardo'];
const SECTORS={A:['Cruzeiro do Sul','Chácaras Anhanguera','Chácaras Rio Branco','Jardim Céu Azul','Jardim Oriente','Morada Nobre','Parque das Cachoeiras','Parque Rio Branco','Parque São Bernardo','Valparaiso II','Vila Guaira'],B:['Chácaras Lourdes Meireles','Chácaras Ypiranga A e B','Cidade Jardins','Mansões Recreio Estrela D’Alva','Parque Esplanada','Parque Esplanada II','Parque Esplanada III','Valparaizo I – Etapas A, B, C, D e E'],C:['Florais do Planalto','Loteamento Ipanema','Reserva do Paraiso','Rio das Pedras'],D:['Chácaras Araguaia Glebas B, C e E','Chácaras e Mansões Santa Maria','Cemitério Jardim Metropolitano','Loteamento Pacaembu','Mansões Paraíso Perdido','Parque Araruama'],E:['Chácaras Benvinda','Chácaras Brasil A','Chácaras Brasil B','Chácaras Ipanema','Chácaras Marambaia','Chácaras Pirangy','Chácaras Santa Maria','Chácaras Saia Velha','Jardim dos Ipês','Jardim Jockey Club','Mansões Santa Marina','Mansões Ouro Preto','Parque do Ipê','Parque Esplanada V','Parque Marajó','Parque Santa Rita de Cássia','Unimorar','Vale do Sol','Vila Izabel','Vila Saionara']};
let S=load(),map=null,markers=null,routeLine=null,gpsWatch=null,cameraStream=null,selected=null,toastTimer=null;
function base(){return{orders:[],route:[],routeGeo:null,gps:null,addressMemory:{},history:[],settings:{waApi:'',notify:true,arrivalRadius:90},startedAt:null}}
function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem('jtTurboV18')||localStorage.getItem('jtTurboV17')||localStorage.getItem('jtTurboV16');const x=Object.assign(base(),raw?JSON.parse(raw):{});x.orders=(x.orders||[]).map(o=>Object.assign({status:'pending'},o));x.addressMemory=x.addressMemory||{};return x}catch(e){return base()}}
function save(){localStorage.setItem(KEY,JSON.stringify(S));render();drawMap()}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('on');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('on'),4500)}
function modal(t,h){document.getElementById('mt').textContent=t;document.getElementById('mb').innerHTML=h;document.getElementById('modal').classList.add('on')}
function closeModal(){document.getElementById('modal').classList.remove('on');stopCamera()}
function phone(p){let d=String(p||'').replace(/\D/g,'');return(d.length===10||d.length===11)?'55'+d:d}
function norm(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\bq(?:uadra)?\s*[:.]?\s*(\d+[A-Za-z]?)\b/ig,'Quadra $1').replace(/\bqd\s*([0-9A-Za-z]+)\b/ig,'Quadra $1').replace(/\br(?:ua)?\s*[:.]?\s*(\d+[A-Za-z]?)\b/ig,'Rua $1').replace(/\s+/g,' ').trim()}
function parseQR(s){const t=String(s||'');let q=(t.match(/\b(?:q|qd|quadra)\s*[:.]?\s*(\d+[A-Za-z]?)\b/i)||[])[1]||'';let r=(t.match(/\b(?:r|rua)\s*[:.]?\s*(\d+[A-Za-z]?)\b/i)||[])[1]||'';return{q,r}}
function addr(o){return[o.address,o.number,o.sector,o.city||'Valparaiso de Goiás',o.state||'GO'].filter(Boolean).join(', ')}
function keyAddr(o){return norm([o.address,o.number,o.sector].filter(Boolean).join(' ')).toLowerCase()}
function sectorGuess(text){const t=String(text||'').toLowerCase();return NEIGH.find(n=>t.includes(n.toLowerCase()))||''}
function statusText(o){return o.status==='done'?'Concluída':o.status==='arrived'?'Cheguei':o.status==='going'?'A caminho':'Pendente'}
function distance(a,b){const R=6371000,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function initMap(){if(map)return;map=L.map('map').setView(CENTER,13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);markers=L.layerGroup().addTo(map);map.on('click',e=>{if(!selected)return;setPin(selected,e.latlng.lat,e.latlng.lng,'manual');selected=null;toast('📍 Pin salvo. Endereço agora usa esta coordenada.')})}
function drawMap(){initMap();markers.clearLayers();if(routeLine){routeLine.remove();routeLine=null}S.orders.forEach((o,i)=>{if(o.lat==null||o.lng==null)return;const ic=L.divIcon({className:'',html:'<div class="pin '+(o.status==='done'?'done':'')+'">'+(i+1)+'</div>',iconSize:[34,34],iconAnchor:[17,17]});L.marker([o.lat,o.lng],{icon:ic}).addTo(markers).bindPopup('<b>'+(i+1)+'. '+esc(o.name||'Cliente')+'</b><br>'+esc(addr(o))+'<br><br><button class="o" onclick="goDelivery(\''+o.id+'\')">🧭 Ir</button> <button onclick="openFacade(\''+o.id+'\')">🏠 Fachada</button>')});if(S.gps)L.marker([S.gps.lat,S.gps.lng],{icon:L.divIcon({className:'',html:'<div class="me">📍</div>',iconSize:[38,38],iconAnchor:[19,19]})}).addTo(markers).bindPopup('Você está aqui • ±'+Math.round(S.gps.accuracy||0)+' m');if(S.routeGeo)routeLine=L.geoJSON(S.routeGeo,{style:{weight:6,opacity:.85}}).addTo(map)}
function fit(){initMap();let p=S.orders.filter(o=>o.lat!=null&&o.lng!=null).map(o=>[o.lat,o.lng]);if(S.gps)p.push([S.gps.lat,S.gps.lng]);if(p.length)map.fitBounds(L.latLngBounds(p).pad(.15));else map.setView(CENTER,13)}
function startGPS(){if(!navigator.geolocation)return gpsHelp('Seu navegador não oferece GPS.');if(gpsWatch!=null){toast('📍 GPS já está ligado.');return}document.getElementById('gpsState').textContent='GPS procurando…';gpsWatch=navigator.geolocation.watchPosition(p=>{const was=S.gps;S.gps={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy,at:Date.now()};document.getElementById('gpsState').textContent='GPS ativo • ±'+Math.round(p.coords.accuracy||0)+' m';if(!was||distance(was,S.gps)>8){localStorage.setItem(KEY,JSON.stringify(S));drawMap();autoArrival()}},e=>{gpsWatch=null;document.getElementById('gpsState').textContent='GPS com erro';gpsHelp(e.code===1?'Permissão de localização negada.':'Não consegui obter sua posição agora.')},{enableHighAccuracy:true,timeout:20000,maximumAge:2000})}
function gpsHelp(t){modal('📍 GPS','<div class="notice"><b>'+esc(t)+'</b><br><br>Ative Localização e permita localização precisa para o navegador. No iPhone: Ajustes → Privacidade e Segurança → Serviços de Localização → navegador → Durante o Uso + Localização Precisa.</div><button class="b wide" onclick="closeModal();startGPS()">🔄 Tentar novamente</button>')}
function currentNext(){const active=S.orders.filter(o=>o.status!=='done');if(!active.length)return null;if(S.route?.length){for(const id of S.route){const o=active.find(x=>x.id===id);if(o)return o}}if(S.gps)return active.filter(o=>o.lat!=null).sort((a,b)=>distance(S.gps,a)-distance(S.gps,b))[0]||active[0];return active[0]}
function routeOrder(){const pool=S.orders.filter(o=>o.status!=='done'&&o.lat!=null&&o.lng!=null);if(!pool.length)return toast('Nenhuma entrega localizada ainda.');let cur=S.gps?{lat:S.gps.lat,lng:S.gps.lng}:{lat:pool[0].lat,lng:pool[0].lng},left=[...pool],out=[];while(left.length){left.sort((a,b)=>distance(cur,a)-distance(cur,b));const n=left.shift();out.push(n.id);cur=n}S.route=out;document.getElementById('routeState').textContent='Rota com '+out.length+' paradas';toast('🛣️ Rota organizada pela proximidade.');buildRoadRoute()}
async function buildRoadRoute(){if(!S.route?.length)return;const pts=S.route.map(id=>S.orders.find(o=>o.id===id)).filter(Boolean);if(pts.length<2){S.routeGeo=null;save();return}const coords=pts.map(o=>o.lng+','+o.lat).join(';');try{const r=await fetch('https://router.project-osrm.org/route/v1/driving/'+coords+'?overview=full&geometries=geojson&steps=false');const j=await r.json();if(j.code!=='Ok')throw Error();S.routeGeo=j.routes[0].geometry;document.getElementById('routeInfo').textContent=(j.routes[0].distance/1000).toFixed(1)+' km • '+Math.round(j.routes[0].duration/60)+' min pela malha viária';save()}catch(e){S.routeGeo=null;document.getElementById('routeInfo').textContent='Sequência pronta; linha viária indisponível agora.';save()}}
function navigateUrl(o){if(!o)return '';const dest=o.lat!=null?o.lat+','+o.lng:encodeURIComponent(addr(o));return'https://www.google.com/maps/dir/?api=1&destination='+dest+'&travelmode=driving'}
function goDelivery(id){const o=S.orders.find(x=>x.id===id)||currentNext();if(!o)return toast('Não há entrega para navegar.');o.status='going';o.goingAt=o.goingAt||Date.now();save();openExternal(navigateUrl(o));notify('🚚 Indo para '+(o.name||'a próxima entrega'),'A rota foi aberta.')}
function navigateNext(){goDelivery(currentNext()?.id)}
function openExternal(u){window.open(u,'_blank','noopener')}
function autoArrival(){const o=currentNext();if(!o||o.lat==null||!S.gps)return;const d=distance(S.gps,o);if(d<=250&&!o.prepNotified){o.prepNotified=true;save();notify('📍 Você está chegando','Prepare a próxima entrega: '+(o.name||'cliente')+'.')}if(d<=Number(S.settings.arrivalRadius||90)&&o.status!=='done'&&o.status!=='arrived'){o.status='arrived';o.arrivedAt=Date.now();save();notify('🏠 Chegou!','Você está a aproximadamente '+Math.round(d)+' m da entrega.');toast('🏠 CHEGOU: '+(o.name||'cliente'))}}
function arrived(){const o=currentNext();if(!o)return;if(o.status==='done')return toast('Essa entrega já foi concluída.');o.status='arrived';o.arrivedAt=Date.now();save();notify('🏠 Cheguei','Entrega marcada como chegada.')}
function complete(id){const o=S.orders.find(x=>x.id===id);if(!o)return;o.status='done';o.doneAt=Date.now();save();notify('✅ Entrega concluída',o.name||'Cliente');const n=currentNext();if(n)notify('➡️ Próxima entrega',n.name||'Cliente')}
function openFacade(id){const o=S.orders.find(x=>x.id===id);if(!o)return;if(o.lat==null)return modal('🏠 Fachada','<div class="notice">Ainda não existe coordenada confiável para esta entrega. Primeiro localize o endereço ou marque a casa no mapa.</div>');const u='https://www.google.com/maps/@?api=1&map_action=pano&viewpoint='+o.lat+','+o.lng;modal('🏠 Fachada • '+esc(o.name||'cliente'),'<div class="notice">A fachada é consultada pela localização real. O Turbo não tira foto da fachada com a câmera.</div><button class="b wide" onclick="openExternal(\''+u+'\')">🏠 Abrir Street View</button><button class="soft wide" style="margin-top:7px" onclick="openExternal(\'https://www.google.com/maps/@'+o.lat+','+o.lng+',19z/data=!3m1!1e3\')">🛰️ Abrir satélite</button>')}
function setPin(id,lat,lng,source){const o=S.orders.find(x=>x.id===id);if(!o)return;o.lat=lat;o.lng=lng;o.locationSource=source;o.locationAt=Date.now();o.confidence=source==='manual'?1:.85;S.addressMemory[keyAddr(o)]={lat,lng,source,display:o.display||addr(o),seenAt:Date.now()};save();toast('📍 Localização gravada na memória do Turbo.')}
function manual(){const o=currentNext()||S.orders.find(x=>x.lat==null);if(!o)return toast('Adicione uma entrega primeiro.');selected=o.id;document.getElementById('mapSec').scrollIntoView({behavior:'smooth'});toast('🎯 Toque exatamente na casa no mapa para marcar '+(o.name||'o cliente')+'.')}
function locateAll(){const list=S.orders.filter(o=>o.status!=='done'&&o.lat==null);if(!list.length)return toast('Não há endereços pendentes.');let i=0;const next=async()=>{if(i>=list.length)return toast('🧠 Localização concluída.');const o=list[i++];document.getElementById('mapStatus').textContent='Localizando '+(o.name||'cliente')+' ('+i+'/'+list.length+')…';await locate(o);setTimeout(next,900)};next()}
async function locate(o){const k=keyAddr(o);if(S.addressMemory[k]){const m=S.addressMemory[k];o.lat=m.lat;o.lng=m.lng;o.locationSource='memoria';o.confidence=.95;save();return true}const qr=parseQR(o.address),sector=o.sector||sectorGuess(o.address),variants=[];if(qr.q&&qr.r)variants.push('Quadra '+qr.q+' Rua '+qr.r+(sector?', '+sector:''));if(o.address)variants.push(o.address+(o.number?', '+o.number:'')+(sector?', '+sector:''));if(o.address)variants.push(norm(o.address));for(const q of variants){try{const u='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=br&q='+encodeURIComponent(q+', '+CITY);const r=await fetch(u,{headers:{Accept:'application/json'}}),a=await r.json(),best=scoreCandidates(a,sector,qr);if(best){o.lat=+best.lat;o.lng=+best.lon;o.display=best.display_name;o.locationSource='geocoding';o.confidence=best._score;S.addressMemory[k]={lat:o.lat,lng:o.lng,source:'geocoding',display:o.display,seenAt:Date.now()};save();return true}}catch(e){}}o.locationError='Não localizado automaticamente';return false}
function scoreCandidates(a,sector,qr){let best=null;for(const x of a||[]){const d=(x.display_name||'').toLowerCase();let s=0;if(d.includes('valparaíso de goiás'))s+=.55;if(d.includes('goiás'))s+=.1;if(sector&&d.includes(sector.toLowerCase()))s+=.2;if(qr.q&&d.includes(qr.q))s+=.08;if(qr.r&&d.includes(qr.r))s+=.08;if(x.type==='house'||x.type==='building')s+=.1;if(s>=(best?best._score:0))best=Object.assign(x,{_score:Math.min(1,s)})}return best&&best._score>=.55?best:null}
function editOrder(id){const o=S.orders.find(x=>x.id===id);if(!o)return;modal('✏️ Editar entrega','<label class="label">Nome</label><input id="eName" class="field" value="'+esc(o.name)+'"><label class="label">WhatsApp</label><input id="ePhone" class="field" value="'+esc(o.phone)+'"><label class="label">Endereço</label><input id="eAddr" class="field" value="'+esc(o.address)+'"><label class="label">Número</label><input id="eNum" class="field" value="'+esc(o.number)+'"><label class="label">Setor/bairro</label><input id="eSector" class="field" value="'+esc(o.sector||'')+'"><button class="o wide" onclick="saveEdit(\''+id+'\')">💾 Salvar e localizar</button>')}
function saveEdit(id){const o=S.orders.find(x=>x.id===id);if(!o)return;o.name=document.getElementById('eName').value;o.phone=document.getElementById('ePhone').value;o.address=document.getElementById('eAddr').value;o.number=document.getElementById('eNum').value;o.sector=document.getElementById('eSector').value;o.lat=null;o.lng=null;closeModal();save();locate(o).then(()=>toast(o.lat?'📍 Endereço localizado.':'⚠️ Não localizado; marque no mapa.'))}
function addManual(){modal('➕ Nova entrega','<label class="label">Nome</label><input id="aName" class="field" placeholder="Nome do cliente"><label class="label">WhatsApp</label><input id="aPhone" class="field" placeholder="61999999999"><label class="label">Endereço</label><input id="aAddr" class="field" placeholder="Ex.: Q123 R75"><label class="label">Número</label><input id="aNum" class="field" placeholder="123"><label class="label">Setor/bairro</label><input id="aSector" class="field" placeholder="Ex.: Valparaiso II"><button class="o wide" onclick="saveManual()">💾 Salvar cliente</button>')}
function saveManual(){const o={id:'o'+Date.now(),name:document.getElementById('aName').value.trim()||'Cliente',phone:document.getElementById('aPhone').value.trim(),address:norm(document.getElementById('aAddr').value),number:document.getElementById('aNum').value.trim(),sector:document.getElementById('aSector').value.trim(),status:'pending',createdAt:Date.now()};S.orders.push(o);closeModal();save();locate(o).then(()=>toast(o.lat?'📍 Cliente salvo e localizado.':'⚠️ Cliente salvo; marque a casa no mapa.'))}
function importList(){document.getElementById('file').click()}
document.getElementById('file').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;const text=await f.text(),lines=text.split(/\r?\n/).filter(Boolean);for(let i=0;i<lines.length;i++){const p=lines[i].split(/[;,\t]/);if(i===0&&/nome/i.test(p[0]))continue;S.orders.push({id:'o'+Date.now()+i,name:p[0]||'Cliente',phone:p[1]||'',address:norm(p[2]||''),number:p[3]||'',sector:p[4]||'',status:'pending',createdAt:Date.now()})}save();toast('📦 '+lines.length+' linhas importadas.');locateAll();e.target.value=''})