function capture(){modal('📷 Capturar dados','<div class="notice">A câmera do Turbo é só para <b>nome, WhatsApp, endereço e número</b>. Não fotografa a fachada.</div><video id="cam" class="cam" autoplay playsinline></video><button class="dark wide" onclick="startCamera()">📷 Abrir câmera</button><button class="soft wide" style="margin-top:7px" onclick="ocrCamera()">🔎 Ler texto da imagem</button><div id="ocrOut" class="muted" style="margin-top:8px"></div><div class="grid4" style="margin-top:8px"><button class="o" onclick="addOCR()">💾 Usar dados</button><button class="soft" onclick="closeModal()">Cancelar</button></div>');startCamera()}
async function startCamera(){try{if(cameraStream)return;cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});const v=document.getElementById('cam');if(v)v.srcObject=cameraStream}catch(e){toast('📷 Câmera bloqueada. Permita acesso à câmera.')}}
function stopCamera(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}}
async function ocrCamera(){if(!cameraStream)return toast('Abra a câmera primeiro.');const v=document.getElementById('cam'),c=document.createElement('canvas');c.width=v.videoWidth||900;c.height=v.videoHeight||700;c.getContext('2d').drawImage(v,0,0,c.width,c.height);document.getElementById('ocrOut').textContent='Lendo…';try{const r=await Tesseract.recognize(c,'por');document.getElementById('ocrOut').textContent=r.data.text;window.__ocr=r.data.text}catch(e){document.getElementById('ocrOut').textContent='Não consegui ler; tente uma foto mais nítida.'}}
function addOCR(){const t=window.__ocr||'';if(!t)return toast('Leia a imagem primeiro.');const ph=(t.match(/(?:\+?55\s*)?(?:\(?61\)?\s*)?9?\d{4}[-\s]?\d{4}/)||[])[0]||'',num=(t.match(/\b(?:n[ºo]?|número)\s*[:.]?\s*(\d+[A-Za-z]?)\b/i)||[])[1]||'',lines=t.split(/\n/).map(x=>x.trim()).filter(Boolean),o={id:'o'+Date.now(),name:lines[0]||'Cliente',phone:ph,address:norm(lines.slice(1).join(' ')),number:num,status:'pending',createdAt:Date.now()};S.orders.push(o);closeModal();save();locate(o).then(()=>toast(o.lat?'📍 Dados salvos e endereço localizado.':'⚠️ Dados salvos; localização pendente.'))}
function requestWA(o){const p=phone(o.phone);if(!p)return toast('Cliente sem WhatsApp cadastrado.');const text='Olá '+(o.name||'')+'! 🚚 Sou da J&T. Estou preparando sua entrega. Pode me enviar sua localização atual pelo WhatsApp? 📎 → Localização → Enviar localização atual.';openExternal('https://wa.me/'+p+'?text='+encodeURIComponent(text))}
function whatsapp(){const pending=S.orders.filter(o=>o.status!=='done'&&phone(o.phone));if(!pending.length)return toast('Nenhum WhatsApp disponível.');modal('💬 WhatsApp Business','<div class="notice"><b>Modo Business:</b> se o servidor da Cloud API estiver configurado, o Turbo envia e recebe localização automaticamente. Sem servidor, o botão usa o WhatsApp normal como fallback.</div>'+pending.map((o,i)=>'<div class="candidate"><b>'+(i+1)+'. '+esc(o.name||'Cliente')+'</b><div class="muted">'+esc(addr(o))+'</div><button class="o wide" style="margin-top:6px" onclick="sendWAFlow(\''+o.id+'\')">📍 Pedir localização</button></div>').join(''))}
async function sendWAFlow(id){const o=S.orders.find(x=>x.id===id);if(!o)return;const api=S.settings.waApi;if(!api)return requestWA(o);try{const r=await fetch(api.replace(/\/$/,'')+'/api/whatsapp/send-flow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:phone(o.phone),order:{client:o.name,address:addr(o)}})}),j=await r.json();if(!j.ok)throw Error(j.error||'erro');o.waState='sent';save();toast('💬 Mensagem Business enviada.')}catch(e){toast('⚠️ Business indisponível; abrindo WhatsApp normal.');requestWA(o)}}
function moreSettings(){modal('🔧 Configurações','<label class="label">URL do servidor J&T (WhatsApp Business)</label><input id="waApi" class="field" value="'+esc(S.settings.waApi||'')+'" placeholder="https://seu-servidor"><div class="notice">Não coloque token da Meta aqui. O token deve ficar somente no servidor. O Cloud API precisa de WABA, Phone Number ID, token e webhook HTTPS.</div><label class="label">Raio automático de chegada (metros)</label><input id="rad" class="field" type="number" value="'+(S.settings.arrivalRadius||90)+'"><button class="o wide" onclick="saveSettings()">💾 Salvar</button>')}
function saveSettings(){S.settings.waApi=document.getElementById('waApi').value.trim();S.settings.arrivalRadius=Math.max(30,Math.min(300,+document.getElementById('rad').value||90));closeModal();save();toast('⚙️ Configurações salvas.')}
function municipal(){modal('🗺️ Mapa de Valparaíso','<div class="notice"><b>Uso rápido:</b> Q123 R75 vira Quadra 123 • Rua 75. Use o mapa municipal para conferir a quadra/setor; depois marque a casa no mapa operacional se o geocodificador não achar o ponto.</div><iframe class="refmap" src="../mapa-valparaiso-goias.pdf#view=FitH"></iframe>')}
function memory(){const n=Object.keys(S.addressMemory||{}).length;modal('🧠 Base local','<div class="notice">O Turbo guarda cada endereço que você confirma ou localiza: texto normalizado, coordenada, origem e data. Isso faz a próxima entrega no mesmo endereço ser mais rápida.</div><p><b>'+n+'</b> endereços aprendidos neste aparelho.</p><button class="danger wide" onclick="if(confirm(\'Apagar toda a memória de endereços?\')){S.addressMemory={};save();closeModal()}">Apagar memória</button>')}
function notify(title,body){if(!S.settings.notify)return;if('Notification' in window){if(Notification.permission==='granted')new Notification(title,{body});else if(Notification.permission!=='denied')Notification.requestPermission().catch(()=>{})}}
async function askNotify(){if('Notification' in window&&Notification.permission==='default')await Notification.requestPermission()}
function render(){const total=S.orders.length,loc=S.orders.filter(o=>o.lat!=null).length,pend=S.orders.filter(o=>o.status!=='done').length,done=S.orders.filter(o=>o.status==='done').length;document.getElementById('stTotal').textContent=total;document.getElementById('stLoc').textContent=loc;document.getElementById('stPend').textContent=pend;document.getElementById('stDone').textContent=done;const n=currentNext();document.getElementById('nextText').textContent=n?(n.name+' • '+addr(n)):'Nenhuma entrega pendente.';document.getElementById('nextEta').textContent=n&&S.gps&&n.lat!=null?(Math.round(distance(S.gps,n)/100)/10)+' km':'';document.getElementById('orders').innerHTML=S.orders.map((o,i)=>'<div class="order '+(o.status==='done'?'done':'')+'"><div class="orderhead"><div><div class="name">'+(i+1)+'. '+esc(o.name||'Cliente')+'</div><div class="addr">'+esc(addr(o))+'</div></div><span class="tag '+(o.status==='going'?'go':o.status==='arrived'?'arr':o.status==='done'?'done':'')+'">'+statusText(o)+'</span></div><div class="orderActions"><button class="o" onclick="goDelivery(\''+o.id+'\')">🧭 Ir</button><button class="g" onclick="arriveId(\''+o.id+'\')">📍 Cheguei</button><button class="soft" onclick="openFacade(\''+o.id+'\')">🏠 Fachada</button><button class="soft" onclick="editOrder(\''+o.id+'\')">✏️ Editar</button></div></div>').join('')||'<div class="muted">Nenhuma entrega. Use Capturar ou Cliente.</div>';document.getElementById('moreInfo').textContent='Base local: '+Object.keys(S.addressMemory||{}).length+' endereços • '+NEIGH.length+' bairros/regiões de referência • setores A–E carregados.'}
function arriveId(id){const o=S.orders.find(x=>x.id===id);if(!o)return;o.status='arrived';o.arrivedAt=Date.now();save();notify('🏠 Cheguei',o.name||'Cliente')}
function switchTab(id){document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.getElementById(id).classList.remove('hidden');document.getElementById(id).scrollIntoView({behavior:'smooth',block:'start'});if(id==='mapSec')setTimeout(()=>{initMap();map.invalidateSize()},250)}
document.addEventListener('click',e=>{const a=e.target.closest('[data-a]')?.dataset.a;if(!a)return;const f={start:()=>{startGPS();routeOrder();askNotify()},capture:capture,wa:whatsapp,add:addManual,goNext:navigateNext,arrived:arrived,facade:()=>{const n=currentNext();if(n)openFacade(n.id)},gps:startGPS,route:routeOrder,manual:manual,municipal:municipal,fit:fit,locate:locateAll,import:importList,memory:memory,settings:moreSettings,close:closeModal};if(f[a])f[a]()});
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));
function boot(){render();initMap();drawMap();startGPS();askNotify();if(S.startedAt)document.getElementById('routeState').textContent='Rota em andamento'}boot();