(function(){
  const B=[-16.13,-48.06,-16.00,-47.90],EP='https://overpass-api.de/api/interpreter';
  function addButton(){const box=document.querySelector('#moreSec .grid4');if(!box||document.getElementById('scanBtn'))return;const b=document.createElement('button');b.id='scanBtn';b.className='soft';b.textContent='🔎 Varredura Valparaíso';b.onclick=scanCity;box.appendChild(b)}
  async function query(q){const r=await fetch(EP,{method:'POST',body:'data='+encodeURIComponent(q)});if(!r.ok)throw Error('Overpass '+r.status);return r.json()}
  function center(x){return x.center?[x.center.lat,x.center.lon]:[x.lat,x.lon]}
  function searchMemory(q){const t=String(q||'').toLowerCase();return(S.cityIndex||[]).filter(x=>(x.name+' '+x.number+' '+x.street+' '+x.sector+' '+x.shop+' '+x.amenity).toLowerCase().includes(t)).slice(0,20)}
  async function scanCity(){modal('🔎 Varredura de Valparaíso','<div class="notice">Vou consultar a malha pública para ruas, vias nomeadas, lojas/comércios, serviços e endereços que estejam publicados. Isso entra na memória local. Lotes que não existirem em uma base pública não serão inventados.</div><div id="scanProg">Consultando ruas…</div>');const q1=`[out:json][timeout:120];way["highway"]["name"](${B.join(',')});out center tags;`,q2=`[out:json][timeout:120];(nwr["shop"]["name"](${B.join(',')});nwr["amenity"]["name"](${B.join(',')});nwr["addr:housenumber"](${B.join(',')}););out center tags;`;try{const a=await query(q1);document.getElementById('scanProg').textContent='Ruas encontradas: '+a.elements.length+'. Consultando comércio, serviços e endereços…';const b=await query(q2),all=[...a.elements,...b.elements],idx={};for(const x of all){const t=x.tags||{},name=t.name||t['addr:street']||'';if(!name)continue;const c=center(x);const k=(name+'|'+(t['addr:housenumber']||'')+'|'+(t['addr:postcode']||'')+'|'+(c[0]||'')+'|'+(c[1]||'')).toLowerCase();idx[k]={name,number:t['addr:housenumber']||'',street:t['addr:street']||name,postcode:t['addr:postcode']||'',shop:t.shop||'',amenity:t.amenity||'',lat:c[0],lng:c[1],sector:t['addr:suburb']||t['addr:district']||'',source:'OpenStreetMap',seenAt:Date.now()}}S.cityIndex=Object.values(idx);localStorage.setItem(KEY,JSON.stringify(S));render();drawMap();modal('✅ Varredura concluída','<div class="notice"><b>'+S.cityIndex.length+' referências</b> foram guardadas neste aparelho.</div><p>Quando você digitar uma rua, loja, número ou ponto já varrido, o Turbo pode usar essa memória antes de consultar a internet.</p><button class="o wide" onclick="closeModal()">Continuar</button>')}catch(e){modal('⚠️ Varredura','<div class="notice">A consulta pública não respondeu agora. Tente novamente mais tarde; a base já aprendida no aparelho continua intacta.</div><button class="soft wide" onclick="closeModal()">Fechar</button>')}}
  const oldLocate=window.locate;window.locate=async function(o){const q=(o.address+' '+o.number+' '+(o.sector||'')).trim();const hit=searchMemory(q)||[];if(hit.length){const exact=hit.find(x=>!o.number||String(x.number)===String(o.number))||hit[0];if(exact.lat!=null&&exact.lng!=null){o.lat=Number(exact.lat);o.lng=Number(exact.lng);o.locationSource='base-varrida';o.display=exact.name+' '+exact.number;o.confidence=.88;S.addressMemory[keyAddr(o)]={lat:o.lat,lng:o.lng,source:'base-varrida',display:o.display,seenAt:Date.now()};save();return true}}return oldLocate(o)};
  window.scanCity=scanCity;window.searchCityMemory=searchMemory;setTimeout(addButton,1000);setInterval(addButton,3000);setTimeout(()=>{S.cityIndex=S.cityIndex||[]},500);
})();