(function(){
'use strict';
const KEY='jtTurboV24';
const state=load();
let map,me,markers=[],gpsPos=null,route=[],routeIndex=0,routeMode=false,layerSatellite=null,waWindowCount=0;
const $=id=>document.getElementById(id);
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');return{orders:Array.isArray(x.orders)?x.orders:[],history:Array.isArray(x.history)?x.history:[]}}catch(e){return{orders:[],history:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));$('sync').textContent='☁️ Salvo no aparelho')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('on');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('on'),3000)}
function openModal(title,html){$('mt').textContent=title;$('mb').innerHTML=html;$('modal').classList.add('on')}
function closeModal(){$('modal').classList.remove('on')}
function digits(v){return String(v||'').replace(/\D/g,'')}
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()}
function pending(){return state.orders.filter(o=>o.status!=='done')}
function get(id){return state.orders.find(o=>String(o.id)===String(id))}
function address(o){return [o.address,o.number,o.sector,o.cep,'Valparaíso de Goiás','GO','Brasil'].filter(Boolean).join(', ')}
function external(url){const w=window.open(url,'_blank','noopener');if(!w)location.href=url}
function call(o){const p=digits(o?.phone);if(!p)return toast('Sem telefone cadastrado');location.href='tel:'+p}
function wa(o){const p=digits(o?.phone);if(!p)return toast('Sem WhatsApp/celular');const n=p.length<=11?'55'+p:p;external('https://wa.me/'+n+'?text='+encodeURIComponent('Olá, '+(o.name||'cliente')+'! 👋 Sou da J&T Turbo. Poderia me enviar sua localização atual pelo WhatsApp para eu chegar certinho?'))}
function waAll(){const list=pending().filter(o=>digits(o.phone));if(!list.length)return toast('Nenhum cliente com telefone pendente');list.slice(0,12).forEach((o,i)=>setTimeout(()=>wa(o),i*180));toast('Abrindo '+Math.min(list.length,12)+' conversas do WhatsApp. Confirme o envio em cada conversa.')}
function initMap(){map=L.map('map',{zoomControl:true}).setView([-16.0655,-47.9761],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap contributors'}).addTo(map)}
function redraw(){markers.forEach(m=>map.removeLayer(m));markers=[];state.orders.forEach(o=>{if(Number.isFinite(+o.lat)&&Number.isFinite(+o.lng)){const m=L.marker([+o.lat,+o.lng]).addTo(map);m.bindPopup('<b>📦 '+esc(o.name)+'</b><br>'+esc(address(o)));markers.push(m)}});if(gpsPos){if(me)map.removeLayer(me);me=L.circleMarker([gpsPos.lat,gpsPos.lng],{radius:9}).addTo(map).bindPopup('📍 Você está aqui<br>Precisão ~'+Math.round(gpsPos.acc)+' m')}}
function gps(){if(!navigator.geolocation)return toast('GPS indisponível');navigator.geolocation.getCurrentPosition(p=>{gpsPos={lat:p.coords.latitude,lng:p.coords.longitude,acc:p.coords.accuracy};$('gps').textContent='📍 '+gpsPos.lat.toFixed(5)+', '+gpsPos.lng.toFixed(5);$('status').textContent='📍 Você está aqui • precisão ~'+Math.round(gpsPos.acc)+' m';$('gpsQuality').textContent='GPS '+Math.round(gpsPos.acc)+' m';map.setView([gpsPos.lat,gpsPos.lng],16);redraw();if(routeMode)updateRoute()},e=>{$('gps').textContent='📍 GPS bloqueado';$('status').textContent='⚠️ Ative a localização para navegação precisa';toast('Permita a localização do navegador.')},{enableHighAccuracy:true,timeout:20000,maximumAge:3000})}
async function viaCep(cep){const c=digits(cep);if(c.length!==8)return null;try{const r=await fetch('https://viacep.com.br/ws/'+c+'/json/');const x=await r.json();return x.erro?null:x}catch(e){return null}}
async function geo(q){try{const r=await fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=8&addressdetails=1&countrycodes=br&q='+encodeURIComponent(q));return await r.json()}catch(e){return[]}}
function parse(q){const s=norm(q);return{cep:(s.match(/\b\d{5}-?\d{3}\b/)||[])[0]||'',quad:(s.match(/(?:quadra|qd\.?)\s*([0-9]+[a-z]?)/)||[])[1]||'',lot:(s.match(/(?:lote|lt\.?)\s*([0-9]+[a-z]?)/)||[])[1]||'',street:(s.match(/(?:rua|r\.)\s*([a-z0-9-]+)/)||[])[1]||''}}
function confidence(x,p,v){const t=norm(x.display_name||''), parts=(x.address||{}), z=[];let score=0;
if(p.cep&&t.includes(p.cep))score+=20;
if(v?.logradouro&&t.includes(norm(v.logradouro)))score+=30;
if(v?.bairro&&t.includes(norm(v.bairro)))score+=25;
if(p.street&&t.includes(p.street))score+=15;
if(t.includes('valparaiso'))score+=10;
if(p.quad&&t.includes(p.quad))score+=5;
if(p.lot&&t.includes(p.lot))score+=5;
return Math.min(99,score)}
async function resolve(q){
 const p=parse(q);let v=await viaCep(p.cep);const queries=[];
 if(v){if(p.quad&&v.logradouro)queries.push(v.logradouro+', Quadra '+p.quad+', '+(v.bairro||'')+', Valparaíso de Goiás, GO, Brasil');queries.push((v.logradouro||'')+', '+(v.bairro||'')+', Valparaíso de Goiás, GO, Brasil')}
 queries.push(q+', Valparaíso de Goiás, GO, Brasil');queries.push(q+', GO, Brasil');
 const all=[];
 for(const q2 of queries){const r=await geo(q2);r.forEach(x=>x.__score=confidence(x,p,v));all.push(...r);if(r.some(x=>x.__score>=75))break}
 const uniq=[];const seen=new Set();all.sort((a,b)=>(b.__score||0)-(a.__score||0)).forEach(x=>{const k=x.lat+','+x.lon;if(!seen.has(k)){seen.add(k);uniq.push(x)}});return uniq.slice(0,6)
}
async function locate(o){
 const q=address(o);if(!q.trim())return false;
 toast('🔎 Conferindo '+o.name+'...');
 const r=await resolve(q);if(!r.length){o.resolveStatus='needs confirmation';o.confidence=0;save();render();return false}
 const x=r[0];o.lat=+x.lat;o.lng=+x.lon;o.display=x.display_name;o.confidence=x.__score||50;o.resolveStatus=o.confidence>=75?'strong':o.confidence>=45?'approximate':'weak';save();render();map.setView([o.lat,o.lng],18);redraw();return true
}
function nav(o){if(!o)return;if(Number.isFinite(+o.lat)&&Number.isFinite(+o.lng)){external('https://www.google.com/maps/dir/?api=1&destination='+o.lat+','+o.lng+'&travelmode=driving&dir_action=navigate')}else locate(o).then(ok=>ok?nav(o):external('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(address(o))))}
function hav(a,b){const R=6371,la=(+b.lat-a.lat)*Math.PI/180,lo=(+b.lng-a.lng)*Math.PI/180;const z=Math.sin(la/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(+b.lat*Math.PI/180)*Math.sin(lo/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
async function routeTime(o){if(!gpsPos||!o)return;try{const r=await fetch('https://router.project-osrm.org/route/v1/driving/'+gpsPos.lng+','+gpsPos.lat+';'+o.lng+','+o.lat+'?overview=false');const x=await r.json();if(x.routes?.[0])$('routeEta').textContent='📏 '+(x.routes[0].distance/1000).toFixed(1)+' km • ⏱️ ~'+Math.round(x.routes[0].duration/60)+' min'}catch(e){$('routeEta').textContent='🧭 Navegação pronta'}}
async function startRoute(){let list=pending();if(!list.length)return toast('Cadastre entregas primeiro');for(const o of list){if(!Number.isFinite(+o.lat)||!Number.isFinite(+o.lng)){const ok=await locate(o);if(!ok)return toast('Não consegui confirmar '+o.name+'. Peça a localização pelo WhatsApp.')}}list=pending().slice();route=[];let cur=gpsPos||{lat:+list[0].lat,lng:+list[0].lng};while(list.length){list.sort((a,b)=>hav(cur,a)-hav(cur,b));const o=list.shift();route.push(o);cur={lat:+o.lat,lng:+o.lng}}routeIndex=0;routeMode=true;$('routeCard').classList.remove('hidden');$('modeRoute').click();updateRoute();toast('🚚 Rota organizada com '+route.length+' paradas')}
function current(){return routeMode?route[routeIndex]:pending()[0]}
function updateRoute(){const o=current();if(!o){routeMode=false;$('routeCard').classList.add('hidden');$('modeDepot').click();return}$('routeName').textContent=o.name;$('routeAddr').textContent=address(o)+(o.confidence?' • '+o.confidence+'%':'');$('routePos').textContent=(routeIndex+1)+'/'+route.length;$('gpsQuality').textContent=gpsPos?'GPS '+Math.round(gpsPos.acc)+' m':'GPS —';routeTime(o);map.setView([+o.lat,+o.lng],18);redraw()}
function finish(ok){const o=current();if(!o)return;if(ok){o.status='done';o.deliveredAt=new Date().toISOString();state.history.push({...o});routeIndex++;save();render();updateRoute();toast('✓ Entregue. Próxima parada.')}else{o.status='pending';o.attempts=(o.attempts||0)+1;o.lastAttempt=new Date().toISOString();const failed=o;route.splice(routeIndex,1);route.push(failed);if(routeIndex>=route.length)routeIndex=0;save();render();updateRoute();toast('⚠️ Não entregue. Ficou pendente e foi para o fim da rota.')}}
function arrive(){const o=current();if(!o)return;o.arrivedAt=new Date().toISOString();save();const d=gpsPos&&Number.isFinite(+o.lat)?hav(gpsPos,o)*1000:null;if(d!==null&&gpsPos.acc<60&&d>Math.max(60,gpsPos.acc*1.5))toast('🟡 GPS indica '+Math.round(d)+' m do ponto. Confira antes de entregar.');else toast('🟢 Chegada registrada.')}
function edit(id){const o=id?get(id):null;openModal(o?'✏️ Editar entrega':'➕ Nova entrega',\`<input id="fn" class="field" placeholder="Nome *" value="\${esc(o?.name)}"><input id="fp" class="field" placeholder="Celular / WhatsApp" value="\${esc(o?.phone)}"><input id="fa" class="field" placeholder="Rua / avenida" value="\${esc(o?.address)}"><input id="fi" class="field" placeholder="Número / lote" value="\${esc(o?.number)}"><input id="fs" class="field" placeholder="Bairro / setor / quadra" value="\${esc(o?.sector)}"><input id="fc" class="field" placeholder="CEP" value="\${esc(o?.cep)}"><div class="btnrow" style="margin-top:7px"><button id="sv">SALVAR E LOCALIZAR</button><button id="rq" class="secondary">💬 PEDIR LOCALIZAÇÃO</button></div>\`);$('sv').onclick=async()=>{const name=$('fn').value.trim();if(!name)return toast('Informe o nome');const x=o||{id:String(Date.now())+Math.random(),status:'pending'};Object.assign(x,{name,phone:$('fp').value.trim(),address:$('fa').value.trim(),number:$('fi').value.trim(),sector:$('fs').value.trim(),cep:$('fc').value.trim()});if(!o)state.orders.push(x);save();closeModal();render();if(address(x))await locate(x)};$('rq').onclick=()=>wa({name:$('fn').value.trim(),phone:$('fp').value.trim()})}
function status(o){if(o.status==='done')return ['ENTREGUE','ok'];if(o.attempts)return ['PENDENTE • '+o.attempts+' tentativa(s)','bad'];if(o.confidence>=75)return ['ENDEREÇO FORTE','ok'];if(o.confidence>=45)return ['APROXIMADO','warn'];return ['CONFERIR','warn']}
function render(){const p=pending();$('pending').textContent=p.length;$('done').textContent=state.orders.filter(o=>o.status==='done').length;$('failed').textContent=state.orders.filter(o=>o.status==='failed').length;$('total').textContent=state.orders.length;$('summary').textContent=p.length?p.length+' pendente(s) • '+state.orders.filter(o=>o.confidence>=75).length+' endereços bem identificados':'Nenhuma entrega pendente';$('listCount').textContent=state.orders.length+' total';
 $('list').innerHTML=state.orders.length?state.orders.map(o=>{const [st,cl]=status(o);const conf=Math.max(0,Math.min(100,+o.confidence||0));return \`<div class="pkg"><div class="pkghead"><strong>\${esc(o.name)}</strong><span class="badge \${cl}">\${st}</span></div><div class="small">📍 \${esc(address(o))}</div><div class="small">📱 \${esc(o.phone||'Sem telefone')} • \${Number.isFinite(+o.lat)?'coordenada salva':'sem coordenada'}</div><div class="confidence"><i style="width:\${conf}%"></i></div><div class="tiny">Qualidade do endereço: \${conf}% \${o.resolveStatus==='needs confirmation'?'• precisa confirmação':''}</div><div class="pkgactions"><button data-act="edit" data-id="\${o.id}">✏️ EDITAR</button><button data-act="call" data-id="\${o.id}">☎️ LIGAR</button><button data-act="wa" data-id="\${o.id}">💬 WHATS</button><button data-act="find" data-id="\${o.id}">🔎 ACHAR</button><button data-act="nav" data-id="\${o.id}">🧭 IR</button><button data-act="facade" data-id="\${o.id}">🏠 VER LOCAL</button><button class="green" data-act="done" data-id="\${o.id}">✓ ENTREGUE</button><button class="red" data-act="fail" data-id="\${o.id}">✕ NÃO</button></div></div>\`}).join(''):'<div class="empty">Nenhuma entrega cadastrada.<br><button id="emptyAdd" style="margin-top:9px">＋ ADICIONAR ENTREGA</button></div>';redraw();if($('emptyAdd'))$('emptyAdd').onclick=()=>edit()}
function importFile(file){const r=new FileReader();r.onload=()=>{try{const t=String(r.result);let arr;if(/\\.json$/i.test(file.name)){arr=JSON.parse(t);arr=Array.isArray(arr)?arr:(arr.orders||[])}else arr=t.split(/\r?\n/).filter(Boolean).map(l=>{const a=l.split(/[;,]/);return{name:a[0],phone:a[1],address:a[2],number:a[3],sector:a[4],cep:a[5]}});arr.forEach(x=>state.orders.push({id:String(Date.now())+Math.random(),name:x.name||x.nome||'Cliente',phone:x.phone||x.telefone||x.whatsapp||'',address:x.address||x.endereco||'',number:x.number||x.numero||x.lote||'',sector:x.sector||x.bairro||x.quadra||'',cep:x.cep||x.CEP||'',lat:x.lat,lng:x.lng,status:'pending'}));save();render();toast('✓ '+arr.length+' entrega(s) importada(s)')}catch(e){toast('Erro ao importar arquivo')}};r.readAsText(file)}
function quick(){const q=$('quick').value.trim();if(!q)return toast('Digite o endereço');toast('🔎 Procurando no mapa municipal + geocodificador...');resolve(q).then(r=>{$('results').innerHTML=r.length?r.map((x,i)=>\`<div class="result"><strong>\${i+1}. \${esc(x.display_name)}</strong><div class="small">Confiança: \${x.__score||0}%</div><button data-res="\${i}" style="width:100%;margin-top:7px">📍 USAR ESTE PONTO</button></div>\`).join(''):'<div class="notice amber">Não encontrei ponto confiável. Use o WhatsApp para pedir a localização exata.';window.__results=r})}
function useResult(i){const x=window.__results?.[i],o=current();if(!x||!o)return toast('Cadastre ou selecione uma entrega');o.lat=+x.lat;o.lng=+x.lon;o.display=x.display_name;o.confidence=x.__score||50;o.resolveStatus='manual-confirmed';save();render();map.setView([o.lat,o.lng],18);toast('✓ Ponto confirmado para '+o.name)}
function municipal(){openModal('🏛️ Mapa municipal de Valparaíso',\`<div class="notice green">O índice municipal do app contém ruas e quadras do mapa municipal. Ele é usado para conferir referências; GPS/geocodificação continuam responsáveis pelas coordenadas.</div><div class="btnrow" style="margin-top:9px"><button id="pdfOpen">📄 ABRIR PDF MUNICIPAL</button><button id="gm" class="secondary">🌐 GOOGLE MAPS</button></div><div class="result"><b>Referências carregadas</b><div class="small">\${window.JT_MUNICIPAL_INDEX?.streets?.length||0} ruas • \${window.JT_MUNICIPAL_INDEX?.quadras?.length||0} quadras</div></div>\`);$('pdfOpen').onclick=()=>{closeModal();window.open('../mapa-valparaiso-goias.pdf','_blank','noopener')};$('gm').onclick=()=>external('https://www.google.com/maps/search/?api=1&query=Valparaiso+de+Goias+GO')}
function history(){const pend=pending();const hist=state.history.slice(-30).reverse();openModal('🕘 Histórico e pendentes',\`<div class="notice amber">Pendentes agora: \${pend.length}</div>\`+(hist.length?hist.map(o=>\`<div class="pkg"><b>\${esc(o.name)}</b><div class="small">\${esc(address(o))}</div></div>\`).join(''):'<div class="empty">Nenhuma entrega concluída ainda.</div>'))}
function setMode(routeOn){$('modeDepot').classList.toggle('on',!routeOn);$('modeRoute').classList.toggle('on',routeOn);$('headline').textContent=routeOn?'Tela limpa para executar a rota, sem excesso de botões.':'Prepare, confira e organize as encomendas antes de sair.';if(routeOn&&route.length)document.getElementById('routeCard').scrollIntoView({behavior:'smooth',block:'start'})}
function bind(){
 $('modeDepot').onclick=()=>setMode(false);$('modeRoute').onclick=()=>{if(!route.length)return toast('Inicie uma rota primeiro');setMode(true)};
 $('manual').onclick=()=>edit();$('import').onclick=()=>$('file').click();$('file').onchange=e=>{if(e.target.files[0])importFile(e.target.files[0])};
 $('start').onclick=startRoute;$('reload').onclick=gps;$('all').onclick=()=>{const a=state.orders.filter(o=>Number.isFinite(+o.lat)&&Number.isFinite(+o.lng)).map(o=>[+o.lat,+o.lng]);if(a.length)map.fitBounds(a,{padding:[30,30]});else toast('Nenhuma entrega com coordenada')};
 $('sat').onclick=()=>{if(gpsPos)external('https://www.google.com/maps/@?api=1&map_action=map&center='+gpsPos.lat+','+gpsPos.lng+'&zoom=18&basemap=satellite');else gps()};
 $('quickGo').onclick=quick;$('municipal').onclick=municipal;$('history').onclick=history;$('waAll').onclick=waAll;$('street').onclick=()=>{const o=current();if(o)nav(o)};
 $('routeGo').onclick=()=>nav(current());$('routeCall').onclick=()=>call(current());$('routeWa').onclick=()=>wa(current());$('routeArrive').onclick=arrive;$('routeDone').onclick=()=>finish(true);$('routeFail').onclick=()=>finish(false);
 $('list').onclick=e=>{const b=e.target.closest('button');if(!b)return;const o=get(b.dataset.id);if(!o)return;const a=b.dataset.act;if(a==='edit')edit(o.id);if(a==='call')call(o);if(a==='wa')wa(o);if(a==='find')locate(o);if(a==='nav')nav(o);if(a==='facade')external('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(address(o)));if(a==='done'){o.status='done';state.history.push({...o});save();render();toast('✓ Entregue')}if(a==='fail'){o.status='pending';o.attempts=(o.attempts||0)+1;save();render();toast('⚠️ Ficou pendente')}};
 $('results').onclick=e=>{const b=e.target.closest('[data-res]');if(b)useResult(+b.dataset.res)};$('close').onclick=closeModal;$('modal').onclick=e=>{if(e.target===$('modal'))closeModal()};
}
function upgradeCss(){const s=document.createElement('style');s.textContent='.old{display:none!important}';document.head.appendChild(s)}
function boot(){initMap();bind();render();gps();$('sync').textContent='☁️ Local';}
window.JTTurboV24={edit,nav,wa,locate,startRoute};boot();
})();