(function(){'use strict';
var KEY='jtTurboV23';
function E(id){return document.getElementById(id)}
function show(title,body){var m=E('modal');if(!m)return;E('mt').textContent=title;E('mb').innerHTML=body;m.className='modal on';m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function close(){var m=E('modal');if(m){m.className='modal';m.setAttribute('aria-hidden','true');document.body.style.overflow=''}}
function toast(t){if(window.__jtV23&&window.__jtV23.toast)return window.__jtV23.toast(t);var x=E('toast');if(x){x.textContent=t;x.className='toast on';setTimeout(function(){x.className='toast'},2200)}}
function data(){try{var x=JSON.parse(localStorage.getItem(KEY)||'{}');return{orders:Array.isArray(x.orders)?x.orders:[],history:Array.isArray(x.history)?x.history:[]}}catch(e){return{orders:[],history:[]}}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function parseCoords(s){s=String(s||'').trim();var m=s.match(/(-?\d{1,3}(?:[.,]\d+)?)[\s,;]+(-?\d{1,3}(?:[.,]\d+)?)/);if(m){var a=parseFloat(m[1].replace(',','.')),b=parseFloat(m[2].replace(',','.'));if(Math.abs(a)<=90&&Math.abs(b)<=180)return{lat:a,lng:b};if(Math.abs(a)<=180&&Math.abs(b)<=90)return{lat:b,lng:a}}var at=s.match(/@(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/);if(at)return{lat:+at[1],lng:+at[2]};var q=s.match(/[?&](?:q|query|ll|center)=(-?\d+(?:\.\d+)?)[,%20]+(-?\d+(?:\.\d+)?)/i);if(q)return{lat:+q[1],lng:+q[2]};return null}
function parsePhone(s){var m=String(s||'').match(/(?:\+?55\s*)?(?:\(?\d{2}\)?\s*)?\d{4,5}[\s.-]?\d{4}/);return m?m[0]:''}
function parseText(t){var c=parseCoords(t),ph=parsePhone(t),cep=(t.match(/\b\d{5}-?\d{3}\b/)||[])[0]||'';return{coords:c,phone:ph,cep:cep}}
function openPaste(){
 show('📍 LOCALIZAÇÃO DO CLIENTE','<div class="waHelp"><b>O cliente mandou a localização pelo WhatsApp?</b><br>Abra a mensagem dele, copie a <b>latitude e longitude</b> ou o <b>link da localização do Google Maps</b> e cole abaixo.</div><label>📍 Localização do WhatsApp</label><textarea id="pCoords" class="field" rows="3" placeholder="Ex.: -15.873210, -48.045670\nOu cole o link do Google Maps"></textarea><button id="pPasteBtn" style="width:100%">📋 COLAR O QUE O CLIENTE MANDOU</button><div id="pCoordStatus" class="coordStatus">🟡 Aguardando latitude e longitude</div><div class="sectionLabel">DADOS DO CLIENTE</div><input id="pName" class="field" placeholder="👤 Nome do cliente"><input id="pPhone" class="field" type="tel" inputmode="tel" placeholder="📱 Número de celular / WhatsApp"><input id="pAddr" class="field" placeholder="🏠 Endereço"><div class="two"><input id="pNumber" class="field" placeholder="🔢 Número / lote"><input id="pSector" class="field" placeholder="🏘️ Bairro / quadra"></div><input id="pCep" class="field" inputmode="numeric" placeholder="📮 CEP"><textarea id="pNote" class="field" rows="2" placeholder="📝 Observação (opcional)"></textarea><button id="pSave" class="green" style="width:100%;margin-top:8px;font-size:15px">✓ SALVAR ENTREGA</button>');
 function refresh(){var raw=E('pCoords').value,c=parseCoords(raw),x=parseText(raw);if(x.phone&&!E('pPhone').value)E('pPhone').value=x.phone;if(x.cep&&!E('pCep').value)E('pCep').value=x.cep;if(c)E('pCoordStatus').innerHTML='🟢 <b>LOCALIZAÇÃO RECEBIDA</b><br>'+c.lat.toFixed(6)+', '+c.lng.toFixed(6);else E('pCoordStatus').textContent='🟡 Cole latitude/longitude ou o link do Google Maps'}
 E('pCoords').oninput=refresh;
 E('pPasteBtn').onclick=async function(){try{var t=await navigator.clipboard.readText();if(t){E('pCoords').value=t;refresh()}}catch(e){E('pCoords').focus();toast('Agora toque no campo e use Colar do iPhone')}};
 E('pSave').onclick=function(){var c=parseCoords(E('pCoords').value),name=E('pName').value.trim(),phone=E('pPhone').value.trim(),addr=E('pAddr').value.trim();if(!c)return toast('📍 Cole a latitude e longitude da localização do WhatsApp');if(!name)return toast('👤 Coloque o nome do cliente');if(!phone)return toast('📱 Coloque o número de celular');if(!addr)return toast('🏠 Coloque o endereço');var d=data();d.orders.push({id:String(Date.now())+Math.random(),name:name,phone:phone,address:addr,number:E('pNumber').value.trim(),sector:E('pSector').value.trim(),cep:E('pCep').value.trim(),note:E('pNote').value.trim(),lat:c.lat,lng:c.lng,locationSource:'WhatsApp',locationConfirmed:true,confidence:100,status:'pending',createdAt:new Date().toISOString()});save(d);close();toast('✓ Entrega salva com localização exata');setTimeout(function(){location.reload()},250)};
}
function simplify(){
 var style=E('v25CleanStyle');if(!style){style=document.createElement('style');style.id='v25CleanStyle';style.textContent='.waHelp{background:#eef6ff;border:1px solid #cfe2ff;border-radius:12px;padding:12px;line-height:1.45;margin-bottom:12px}.coordStatus{background:#f4f7fb;border:1px solid #dce5ef;border-radius:10px;padding:10px;margin:7px 0 12px;font-size:12px}.sectionLabel{font-size:11px;font-weight:900;color:#087cff;margin:12px 0 3px}.two{display:grid;grid-template-columns:1fr 1fr;gap:6px}@media(max-width:520px){.two{grid-template-columns:1fr}}';document.head.appendChild(style)}
 var tools=[].slice.call(document.querySelectorAll('.card')).find(function(c){var b=c.querySelector('b');return b&&/^Ferramentas/i.test(b.textContent.trim())});if(tools&&!tools.dataset.clean){tools.dataset.clean='1';var b=tools.querySelector('b'),btn=tools.querySelector('.buttons');if(b&&btn){btn.style.display='none';b.style.cursor='pointer';b.innerHTML='⚙️ MAIS FERRAMENTAS';b.onclick=function(){btn.style.display=btn.style.display==='none'?'grid':'none'}}}
 var add=[].slice.call(document.querySelectorAll('.card')).find(function(c){var b=c.querySelector('b');return b&&/Adicionar entrega/i.test(b.textContent)});if(add){var sm=add.querySelector('.small');if(sm)sm.textContent='Cadastre uma entrega ou cole a localização enviada pelo cliente no WhatsApp.';var p=E('paste');if(p)p.textContent='📍 COLAR LOCALIZAÇÃO DO WHATSAPP'}
 var hero=document.querySelector('.hero');if(hero){var s=hero.querySelector('.heroSub');if(s)s.textContent='Cadastre → confirme a localização → faça a rota.';var e=hero.querySelector('.eyebrow');if(e)e.textContent='MODO ENTREGADOR'}
}
function boot(){var p=E('paste');if(p){p.onclick=function(e){e.preventDefault();e.stopPropagation();openPaste();return false};p.addEventListener('click',function(e){e.stopImmediatePropagation()},true)}simplify()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,500)});else setTimeout(boot,500);setInterval(function(){simplify()},2500);
})();